### ISSUE TITLE
How to use author sheets for styling thunderbird GUI?

### ISSUE THREAD

**Issue by Frank-Steiner** [MrOtherGuy/fx-autoconfig#19]
Hi, 
I've installed fx-autoconfig for thunderbird without changing the defaults and it works fine in that I can e.g. style scrollbars for thunderbird in userChrome.ag.css. I also need userChrome.au.css to access e.g. `#msgIdentity::part(label-box){ ...} `
But userChrome.au.css is not loaded because userChrome_au_css.uc.js doesn't come past the `if(script.inbackground && script.isEnabled){` line in function UserChrome_js in boot.jsm.

The comments in userChrome_au_css.uc.js say that it "is loaded only into the document where this script runs which by default is browser.xhtml". So I wonder what I have to do so that it can be loaded for styling the thunderbird GUI?

Thanks a lot!
cu,
Frank

**Comment by MrOtherGuy** [comment]
Hmm. I have never tested with TB, but if it successfully loads the `userChrome.ag.css` then I suppose you should get it to work by adding a new `@include` directive to the `userChrome_au_css.uc.js` header. For example after [line 4](https://github.com/MrOtherGuy/fx-autoconfig/blob/9f3c966eed27e53ba4d18f2d6db5dba4d9b27094/profile/chrome/JS/userChrome_au_css.uc.js#L3) add:

```js
// @name           userChrome_author_css
// @namespace      userChrome_Author_Sheet_CSS
// @include        chrome://messenger/content/messenger.xhtml
// @version        0.0.5
// ...rest-of-the-file
```

By default `boot.jsm` only includes browser.xhtml of Firefox, but since TB is different you need to include its main document.

**Comment by Frank-Steiner** [comment]
What a quick help! And yes, that include works for the main thunderbird window! To enable it also for the messenger composing window I had to add 
```
// @include        chrome://messenger/content/messengercompose/messengercompose.xhtml
```
so now I can style part css in both the main and the composing window. 
Great! Thank you very much!

**Comment by MrOtherGuy** [comment]
Great to hear. So, you didn't make any changes to any of the files? It *just worked*? I probably won't add too much support for TB, but I would sure b glad to know if and how well this works with it.

I'm thinking I *might* make it so that using `@include    main` (which already maps to browser.xhtml) would automatically map to `messenger.xhtml` when used in TB. If I did that, then I would also probably make it so that providing no includes just means `@include    main` which then would map to either browser.xhtml or messenger.xhtml

**Comment by Frank-Steiner** [comment]
I changed userChrome_au_css.uc.js as you said to 
```
// ==UserScript==
// @name           userChrome_author_css
// @namespace      userChrome_Author_Sheet_CSS
// @include        chrome://messenger/content/messenger.xhtml
// @include        chrome://messenger/content/messengercompose/messengercompose.xhtml
// @version        0.0.5
```
and then I could add rules to userChrome.au.css which changed settings for the main and/or the composer window. That's all I had to do. If you consider adding that kind of support for TB it would be nice to automatically include messengercompose.xhtml together with messenger.xhtml. Otherwise a little hint in the readme would also be enough so that people know they just have to add these two lines for TB styling.

**Comment by MrOtherGuy** [comment]
Hmm. I need to think about this. I don't think it's wise to include two documents in the same window by default because I think that makes it too easy to mess up by accident. But certainly the least I could do is to update the readme with some info.

Anyway, thanks for the idea!

**Comment by MrOtherGuy** [comment]
Alright. Status update. I made several changes to boot.jsm so that it better supports Thunderbird.

For you, this means you should now be able to write:

```js
// ==UserScript==
// @name           userChrome_author_css
// @namespace      userChrome_Author_Sheet_CSS
// @include        main
// @include        chrome://messenger/content/messengercompose/messengercompose.xhtml
// @version        0.0.5
```

And if you don't supply **any** `@include` statements, then that script would indeed only run in the main window.

The rest of the changes I made concern the `_ucUtils` object available in your scripts - not all functions are supported (for example loading some url in new tab) but infact most seem to work fine based on my tests (albeit somewhat limited).

Also, this now adds a menu similar to that in Firefox into the `tools` menubar item in the main window.

**Comment by Frank-Steiner** [comment]
Works exactly as you describe, and the menu is also there. Pretty cool, thanks a lot :) It's really great that I'm now able again to style everything in TB my needs.

**Comment by MrOtherGuy** [comment]
Good to hear it works for you as well and not just on my test setup.
