### ISSUE TITLE
Expose ScriptData to scripts and add nsIFile handle to each ScriptData?

### ISSUE THREAD

**Issue by aminomancer** [MrOtherGuy/fx-autoconfig#21]
I'm looking into making a kind of about:userchrome page with a script updater (basically check each script by its downloadURL, optionally update file if versions differ), and it would simplify things if we could do something like this:
```js
_ucUtils.getScriptData().forEach(async scriptData => {
  let row = createScriptRow(scriptData);
  rows.appendChild(row);
  if (scriptData.downloadURL) {
    let remoteScript;
    try {
      let remoteURL = new URL(scriptData.downloadURL);
      let remoteFile = await fetch(remoteURL);
      remoteScript = await remoteFile.text();
    } catch (error) {
      console.log(`Error updating ${scriptData.filename} :>> `, error);
      return;
    }
    let remoteHeader = remoteScript.match(/^\/\/ ==UserScript==\s*\n(?:.*\n)*?\/\/ ==\/UserScript==\s*\n/m);
    let remoteScriptData = new _ucUtils.ScriptData(scriptData.filename, remoteHeader ? remoteHeader[0] : "");
    let currentVersion = scriptData.version;
    let newVersion = remoteScriptData.version;
    if (Services.vc.compare(newVersion, currentVersion) > 0) {
      row.updateButton.textContent = "Download update";
      let { path } = scriptData.fileHandle;
      row.updateButton.addEventListener("click", async event => {
        row.updateButton.disabled = true;
        try {
          await IOUtils.writeUTF8(path, remoteScript, { mode: "overwrite", tmpPath: path + ".tmp" });
          row.updateButton.textContent = "Updated";
          row.versionLabel.textContent = `${currentVersion} — Restart to update to ${newVersion}`;
        } catch (error) {
          console.log(error);
          row.updateButton.textContent = "Update failed";
          row.versionLabel.textContent = `${currentVersion} — Update to ${newVersion} manually`;
        }
      });
      row.updateButton.hidden = false;
    }
  }
});
```
Basically what's missing is fx-autoconfig doesn't expose ScriptData for checking the remote file's version, and the nsIFiles fx-autoconfig creates at startup when loading the scripts aren't stored, so the page would have to recreate them by inferring the file path from the filename. Seems neater to just store them on the ScriptData instance, as part of the `ScriptData.fromFile` method or something.

Technically all I need for this is the script's `path` but I figured the file itself might be useful for something I haven't considered yet. For example, we could check the lastModifiedTime to limit the frequency of fetches.

Thanks!

**Comment by MrOtherGuy** [comment]
That sounds useful.  I'm not sure if it's a good idea to keep those nsIFile objects alive constantly. But we could certainly make it so that getScripts() returns another types of objects that would have a method to get nsIFile instance for it. Something like this:

```javascript
class ScriptInfo{
  constructor(){ }
  
  asFile(){
    return getDirEntry(this.filename, true);
  }
  static fromScript(aScript){
    let info = new ScriptInfo();
    Object.assign(info, aScript);
    info.regex = new RegExp(aScript.regex.source, aScript.regex.flags);
    return info
  }
}
```

So this "view" would be essentially a copy of the metadata that the script manager holds (and no, I don't want to give the real references to scripts), but we can then add some helper methods to these new ScriptInfo objects. How does that sound? 

As for version, I'm not sure what you mean. The objects returned by getScriptInfo() should have a version field, though the value is `undefined` if the script doesn't have a version tag.

**Comment by aminomancer** [comment]
Yeah that file method looks reasonable, thanks.

> As for version, I'm not sure what you mean. The objects returned by getScriptInfo() should have a version field, though the value is `undefined` if the script doesn't have a version tag.

Yeah that works fine. The logic in [nsIVersionComparator](https://searchfox.org/mozilla-central/source/xpcom/base/nsIVersionComparator.idl) is pretty robust, you can do things like
```js
Services.vc.compare("1.0", undefined) == 1
```
and
```js
Services.vc.compare(undefined, undefined) == 0
```
There wouldn't be much point in setting a downloadURL or updateURL if not using the version field, so I don't think we'd reach that point very often. But my goal is basically just to support updating scripts that opt into it, presumably just my own at first but maybe others who are making userChrome.js scripts will take advantage of it in the distant future.

I've done some manual testing, by parsing the remote script's header and running `headerText.match(/\/\/ @version\s+(.+)\s*$/im)?.[1]`, which does work, but since these expressions are basically implementation details for fx-autoconfig, it seems neater if it exposes methods to run the matchers on an arbitrary raw UTF-8 string. Like
```js
class ScriptData {
  ...
  static fromString(aName, aString) {
    const headerText = aString.match(/^\/\/ ==UserScript==\s*\n(?:.*\n)*?\/\/ ==\/UserScript==\s*\n/m);
    return new ScriptData(aName, headerText ? headerText[0] : '');
  }
}
...
utils.getScriptDataFromString = (aName, aString) => {
  let scriptData = ScriptData.fromString(aName, aString);
  let scriptInfo = scriptData.getInfo();
  scriptInfo.isEnabled = !disabledScripts.includes(scriptData.filename);
  return scriptInfo;
}
```
Most scripts won't have a use for this, but I guess that's true for the matchers in general

**Comment by MrOtherGuy** [comment]
What are you trying to do with the ScriptData objects constructed from utf-8 string?

Right now, the manager internally stores script metadata as ScriptData objects, but that isn't exposed to users. What I proposed earlier is to create new ScriptInfo class and when scripts ask utils.getScriptData() they are then given bunch of these ScriptInfo objects. (Naming is a bit confusing but that's beside the point).

So my question is, do you really need or want a way to construct ScriptData objects, and if so, for what purpose? At first glance it would seem to me that getting `ScriptInfo` objects would make more sense, but maybe I don't quite understand what you are aiming for.

Or, hmmm... now that I've thought about this I think you might mean the exact same thing as I do. So no, we don't expose ScriptData to users, but we just need to create one temporarily because all the header matching is done in its constructor. So, essentially you want a way to create these `ScriptInfo` objects from string - that we could totally do.

**Comment by aminomancer** [comment]
Yeah exactly, just need the header matching. I basically just need to fetch the script file from the downloadURL, read it as text, and get the version from the header. And I think the cleanest way of reading the remote script's version field is to use the exact same way fx-autoconfig parsed the local script's version field. The other ScriptData methods aren't necessary, just the header stuff in the constructor.

That way if the matching changes between fx-autoconfig versions, the script doesn't need to be updated and make old versions of fx-autoconfig incompatible. That could also be resolved by adding a version file to fx-autoconfig, though not needing to duplicate the matching expressions would still make my code more concise 😅

**Comment by MrOtherGuy** [comment]
Alright, I added the new API in 11efe27 Check how that works for you.

To use it you would simply do `_ucUtils.parseStringAsScriptInfo(aName, aString)`. The ScriptInfo object you get back has isEnabled field default to `false`  - I suppose it makes sense since it's not representing a "real" script anyway. So, you need to sync it yourself for now.
But, if the `aName` matches one of your scripts, then if you call `.asFile()` on the result it will find the corresponding result on disk.

**Comment by aminomancer** [comment]
Works perfectly, thank you!
