### ISSUE TITLE
Alt+ArrowDown as a hotkey

### ISSUE THREAD

**Issue by rubaboo** [MrOtherGuy/fx-autoconfig#59]
It appears the hotkey validation routine accepts only alphanumeric and function keys. Is that right?

I'd like to invoke backForwardMenu popup with Alt+Down. Would you be able to provide a working example? I don't think I'm quite there yet with my skill level to produce the required `*.uc.js` script entirely on my own.

Thank you!

**Comment by MrOtherGuy** [comment]
Hmm, it appears that the whole hotkey registration api that we provide is really quite broken, for one you cannot add various kinds of hotkeys with it - including alt+down.

I can fix that, or at least make it better than the current situation.

**Comment by MrOtherGuy** [comment]
With latest patch you should now be able to create a window scroped `.uc.js` script like this:

```js
// ==UserScript==
// @onlyonce
// ==/UserScript== 

UC_API.Hotkeys.define({
  key: "VK_DOWN",
  command: (win,hk) => console.log(hk),
  modifiers: "alt",
  id: "myHotkey"
}).autoAttach()
```

You can just supply your callback function as the `command` - the example above will just log the event fired by the hotkey when Alt+ArrowDown is pressed.

**Comment by rubaboo** [comment]
It works, almost. I am trying to use Alt+Down to invoke the tab history menu. The one in the screenshot, to be clear.

So, it works in 2 out of 4 of my browser windows. In the other two, nothing happens. No errors in the console log either. What am I still missing? I tried both extensions, `.uc.js` and `.uc.mjs`, and I removed the `@onlyonce` directive.

Here's my script: [backForwardMenuShortcut.uc.zip](https://github.com/user-attachments/files/18265634/backForwardMenuShortcut.uc.zip)

<img src="https://github.com/user-attachments/assets/650066f6-2ef0-4198-9616-833ef4e8adbc" width=40%>

**Comment by MrOtherGuy** [comment]
Okay, the way you have written this won't work well because you are making a reference at top level to forward button *of a single window*, and the `autoAttach()` method has it's own internal callback that adds the hotkey to all current and future windows when called just once. Now, since you have removed the `@onlyonce` directive, the whole script will run for all windows, and the calls to `autoAttach()` might not do nothing in all but the very first window.

There's bunch of thing happening in during window creation, so there's a good chance that it is non-deterministic which of the functions runs first - if the instance of the full script runs first then your hotkey should work fine I think. But if the internal callback of autoAttach() runs first, then your hotkey will probably try to open the popup in the first window, but that might not do anything because the first window is not active.

There's at least three ways you could do what you want.

Don't make a script-global reference to forward button but instead use getElementById inside the callback function:

```js
// ==UserScript==
// @name                 Back/Forward Menu keyboard shortcut
// @namespace            rubaboo
// @version              1.0
// @description          Alt+Down
// @onlyonce
// ==/UserScript==

UC_API.Hotkeys.define({
  key: "VK_DOWN",
  command: (win,hk) => win.document.getElementById("forward-button")?.menupopup.openPopup(),
  modifiers: "alt",
  id: "myHotkey"
}).autoAttach()
```

Note, I have added back the `@onlyonce` directive, because you don't want to call autoAttach() multiple times - it will get problematic. Since the script runs only once, you can't use the "normal" `document` symbol to query the element (nor store it to global variable) but instead query the element in the callback using the `win` argument that is provided to the callback function.

Alternatively, you could just attach the hotkey to just the current window per window scoped script:

```js
// ==UserScript==
// @name                 Back/Forward Menu keyboard shortcut
// @namespace            rubaboo
// @version              1.0
// @description          Alt+Down
// ==/UserScript==
const fb = document.getElementById("forward-button");
UC_API.Hotkeys.define({
  key: "VK_DOWN",
  command: (win,hk) => fb.menupopup.openPopup(),
  modifiers: "alt",
  id: "myHotkey"
}).attachToWindow(window)
```

Note, here you just call `attachToWindow(window)` with the current window global.

Yet another method, where autoAttach() is also useful is to make a your script a "background module" script with a `.sys.mjs` extension:

```js
// ==UserScript==
// @name                 Back/Forward Menu keyboard shortcut
// @namespace            rubaboo
// @version              1.0
// @description          Alt+Down (.sys.mjs file)
// ==/UserScript==
import { Hotkeys } from "chrome://userchromejs/content/uc_api.sys.mjs";

Hotkeys.define({
  key: "VK_DOWN",
  command: (win,hk) => win.document.getElementById("forward-button")?.menupopup.openPopup(),
  modifiers: "alt",
  id: "myHotkey"
}).autoAttach()
```
Note, in background module .sys.mjs scripts neither `UC_API` or `window` are available. Thus we need to import the Hotkeys symbol from the uc_api.sys.mjs file. The internal callback will then provide you the current window as the first argument of the callback, which you can the use to query the forward button much like in the first example.

Personally, I kinda like this last the most, but I figure that the second example might be the easiest to use.

**Comment by rubaboo** [comment]
Great, all 3 work, including in a new window. I like the first one—makes the most out of `fx-autoconfig` features and looks simplest for it. Are there any pitfalls I need to be aware of, if I end up choosing it? And/or, what are the reasons to prefer the last one?

**Comment by MrOtherGuy** [comment]
The last one is nice because there the callback is one instance of a function that will then get referenced by all the windows where the hotkey gets added to, but the hotkey definition itself lives in the background context.

In the first example the hotkey definition along with the callback, lives in the context of the first window and thus all the windows have a reference the context of first window. That works, but it just feels a bit wrong in my opinion. Also, I'm not actually sure what happens if you were to close the first window. I think it won't cause any issues, but I guess there is a chance that resources from the closed first window might not get cleaned up completely or alternatively that the hotkey stops working in other windows when the first window is closed.

The second example works fine because all the window scoped behavior and hotkey definitions are totally per window.

**Comment by rubaboo** [comment]
Thank you so much. I'm glad I picked this project as my userChrome loader/manager of choice. 🥇 😄 🤝
