### ISSUE TITLE
loadURI for open in background

### ISSUE THREAD

**Issue by Mitezuss** [MrOtherGuy/fx-autoconfig#8]
Maybe the tab is opened on foreground is because is redundant set "where" to 'tabshifted' and set "inBackground" as true.

So, can do 2 things:

1. if "where" is 'tabshifted' then "where"='tab'
2. Remove "inBackground" parameter (let "where"='tabshifted')

Both is working.

**Comment by MrOtherGuy** [comment]
I'm not 100% sure what you asking or suggesting, but I don't think some paramete can be removed. "tabshifted" doesn't mean "open tab in background" but "open tab in background if the default is to open link in foreground for some operation and vice versa.

That being said, it looks like the current logic is not correct either because it links inBackground to where being "tabshifted". So there's perhaps room for improvement there.

**Comment by MrOtherGuy** [comment]
So, I gave this a bit more thought and got to conclusion that the inBackground should just always be false, and let "tabshifted" just always mean in-background.

This means that now `loadURI()` can finally create background tabs.
